### ISSUE TITLE
motif styles

### ISSUE THREAD

**Issue by Fungker** [temporal-graphs/STM#2]
excuse me, i want to know the ITem only identify 16  motif styles  in the paper? or return a collection of  motif

**Comment by purohitsumit** [comment]
Hi @Fungker, ITeM identifies distribution of the 16 "motif style" (with their temporal variations) defined in the paper. So you get a feature vector of the order of size 50.  Thanks

**Comment by Fungker** [comment]
In other words, ITem can return 50 types of modules, including 16 types of
paper

Sumit Purohit <notifications@github.com> 于2020年3月21日周六 下午9:55写道：

**Comment by purohitsumit** [comment]
Those 50 (defined on Figure 3 "Temporal Motif")  are the temporal variations of 16 motif types (defined on Figure 1 "Atomic Motifs"). 

 https://arxiv.org/pdf/2002.08312.pdf

**Comment by Fungker** [comment]
sorry to bother you again, but I am very interested in your work. Since I'm
not good at scala, what data does the ITem finally return,  the number of
50 motif?

Sumit Purohit <notifications@github.com> 于2020年3月21日周六 下午10:04写道：

**Comment by purohitsumit** [comment]
Thanks @Fungker 
ITeM returns a distribution of frequencies of 50 temporal motifs (Fig. 3) which are based on the 16 motif types (Fig 1). Please let me know if i can be any help.

**Comment by Fungker** [comment]
Thank you very much, your method ITem maybe contribute most to my work. Our
work aims to explore the key users by the temporal motif.

Sumit Purohit <notifications@github.com> 于2020年3月21日周六 下午10:29写道：

**Comment by purohitsumit** [comment]
Good to know that. I will be happy to help if you face any issue running the code or following the paper. we are working on various improvements to ITeM's usability and scalability. Is there any paper/presentation of your work i can take a look ? Please send that to Sumit.Purohit@pnnl.gov

**Comment by Fungker** [comment]
Sorry, we don't have some  paper/presentation now,  just an idea for a data
mining competition. I am currently a graduate student with limited
abilities and do not yet understand the code💪. The python version would be
better  😊

Sumit Purohit <notifications@github.com> 于2020年3月21日周六 下午10:45写道：

**Comment by purohitsumit** [comment]
:-) all the best
